version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"  # Expose port 3000 from the container to port 3000 on the host
    volumes:
      - .:/usr/src/app  # Mount the local directory into the container
    environment:
      - NODE_ENV=production
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
